#server {
#	listen 80;
#	#listen 443 ssl;
#	server_name healthismplus.com www.healthismplus.com;
#	index index.php;
#	root /usr/share/nginx/html/php/test_wp;
#	access_log /var/log/nginx/healthismplus.com.access.log;
#	error_log /var/log/nginx/healthismplus.com.error.log;
#	include global/app.conf;
#	location ~* \.(eot|otf|ttf|woff)$ {
#		add_header Access-Control-Allow-Origin *;
#	}
#	#ssl_certificate /etc/letsencrypt/live/admin.healthismplus.com/fullchain.pem; # managed by Certbot
#	#ssl_certificate_key /etc/letsencrypt/live/admin.healthismplus.com/privkey.pem; # managed by Certbot
#	#include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
#	#ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
#}

server {
	listen 443 ssl;
	server_name healthismplus.com www.healthismplus.com;
	index index.php;
	#root /usr/share/nginx/html/php/test_wp;
	root /usr/share/nginx/html/php/healthism_wp;
	
	access_log /var/log/nginx/healthismplus.com.access.log;
	error_log /var/log/nginx/healthismplus.com.error.log;
	
	location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php;
        fastcgi_index   index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
    ssl_certificate /etc/letsencrypt/live/healthismplus.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/healthismplus.com/privkey.pem; # managed by Certbot
	include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot





}

server {
    if ($host = www.healthismplus.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = healthismplus.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	server_name healthismplus.com www.healthismplus.com;
    return 404; # managed by Certbot




}