server {
	listen 443 ssl;
	listen 80;
	server_name admin.healthismplus.com api.healthismplus.com;
	index index.php;
	root /usr/share/nginx/html/php/healthism_live/public;
	access_log /var/log/nginx/admin.healthismplus.com.access.log;
	error_log /var/log/nginx/admin.healthismplus.com.error.log;
	include global/app.conf;
	location ~* \.(eot|otf|ttf|woff)$ {
		add_header Access-Control-Allow-Origin *;
	}
    ssl_certificate /etc/letsencrypt/live/api.healthismplus.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.healthismplus.com/privkey.pem; # managed by Certbot
	include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot








}


#server {
#    if ($host = admin.healthismplus.com) {
#        return 301 https://$host$request_uri;
#    } # managed by Certbot
#
#
#	listen 80;
#	server_name admin.healthismplus.com api.healthismplus.com;
#    return 404; # managed by Certbot
#
#
#}